[2024-05-24T12:49:59.801+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T12:49:59.810+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_from_github_to_s3.download_and_upload_to_s3 manual__2024-05-24T12:49:59.224490+00:00 [queued]>
[2024-05-24T12:49:59.813+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_from_github_to_s3.download_and_upload_to_s3 manual__2024-05-24T12:49:59.224490+00:00 [queued]>
[2024-05-24T12:49:59.813+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-24T12:49:59.818+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_and_upload_to_s3> on 2024-05-24 12:49:59.224490+00:00
[2024-05-24T12:49:59.821+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-24T12:49:59.821+0000] {standard_task_runner.py:63} INFO - Started process 83 to run task
[2024-05-24T12:49:59.822+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_from_github_to_s3', 'download_and_upload_to_s3', 'manual__2024-05-24T12:49:59.224490+00:00', '--job-id', '729', '--raw', '--subdir', 'DAGS_FOLDER/upload_from_github_to_s3_dag.py', '--cfg-path', '/tmp/tmps9kmawr1']
[2024-05-24T12:49:59.822+0000] {standard_task_runner.py:91} INFO - Job 729: Subtask download_and_upload_to_s3
[2024-05-24T12:49:59.838+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_from_github_to_s3.download_and_upload_to_s3 manual__2024-05-24T12:49:59.224490+00:00 [running]> on host 377bad4f8815
[2024-05-24T12:49:59.870+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_from_github_to_s3' AIRFLOW_CTX_TASK_ID='download_and_upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-05-24T12:49:59.224490+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-24T12:49:59.224490+00:00'
[2024-05-24T12:49:59.870+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T12:50:00.699+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-05-24T12:50:00.764+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-24T12:50:00.765+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T12:50:00.769+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=upload_from_github_to_s3, task_id=download_and_upload_to_s3, run_id=manual__2024-05-24T12:49:59.224490+00:00, execution_date=20240524T124959, start_date=20240524T124959, end_date=20240524T125000
[2024-05-24T12:50:00.795+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-24T12:50:00.802+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-24T12:50:00.803+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
